// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLzsq7HP_iSXCZTEatdFsh34wp2uh5urw',
    appId: '1:506310085554:web:509f57753dd97f522bf2ab',
    messagingSenderId: '506310085554',
    projectId: 'confession-fd9ea',
    authDomain: 'confession-fd9ea.firebaseapp.com',
    databaseURL: 'https://confession-fd9ea-default-rtdb.firebaseio.com',
    storageBucket: 'confession-fd9ea.firebasestorage.app',
    measurementId: 'G-10SP2WJ2Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcesDTXz4djZqX7QrA_9f_r9Mm-7_oKs',
    appId: '1:506310085554:android:4d23328a12dc80912bf2ab',
    messagingSenderId: '506310085554',
    projectId: 'confession-fd9ea',
    databaseURL: 'https://confession-fd9ea-default-rtdb.firebaseio.com',
    storageBucket: 'confession-fd9ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOsKiQaev941JkK9IsQRO597wfr69_aoA',
    appId: '1:506310085554:ios:576cce208ddec0a42bf2ab',
    messagingSenderId: '506310085554',
    projectId: 'confession-fd9ea',
    databaseURL: 'https://confession-fd9ea-default-rtdb.firebaseio.com',
    storageBucket: 'confession-fd9ea.firebasestorage.app',
    iosBundleId: 'com.example.confessionAppFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOsKiQaev941JkK9IsQRO597wfr69_aoA',
    appId: '1:506310085554:ios:576cce208ddec0a42bf2ab',
    messagingSenderId: '506310085554',
    projectId: 'confession-fd9ea',
    databaseURL: 'https://confession-fd9ea-default-rtdb.firebaseio.com',
    storageBucket: 'confession-fd9ea.firebasestorage.app',
    iosBundleId: 'com.example.confessionAppFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLzsq7HP_iSXCZTEatdFsh34wp2uh5urw',
    appId: '1:506310085554:web:95520f016a182d732bf2ab',
    messagingSenderId: '506310085554',
    projectId: 'confession-fd9ea',
    authDomain: 'confession-fd9ea.firebaseapp.com',
    databaseURL: 'https://confession-fd9ea-default-rtdb.firebaseio.com',
    storageBucket: 'confession-fd9ea.firebasestorage.app',
    measurementId: 'G-PCT5B1E400',
  );
}
